server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: Mima@123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #Hikari连接池
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 连接池名字
      pool-name: MyHikariCP
      # 最小空闲连接数
      minimum-idle: 10
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 600000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 默认自动提交行为，默认值为true
      auto-commit: true
      # 连接最长生命周期，0表示无限，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间，默认30000，即30秒
      connection-timeout: 30000
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: Mima123456
    timeout: 3000
    lettuce:
      pool:
        # 连接池最大连接数，默认8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
        
global:
  servername: demo
  version: 1.0