CREATE TABLE IF NOT EXISTS `sys_user`(
	`ID` VARCHAR(32) COMMENT "ID",
	`ROLE_IDS` VARCHAR(2000) COMMENT "角色ID",
	`LOGIN_NAME` VARCHAR(32) COMMENT "用户名",
	`PASSWORD` VARCHAR(32) COMMENT "密码",
	`NICK_NAME` VARCHAR(32) UNIQUE COMMENT "昵称",
	`REAL_NAME` VARCHAR(32) COMMENT "真实姓名",
	`GENDER` INT COMMENT "性别",
	`PHONE` VARCHAR(32)  UNIQUE COMMENT "手机号",
	`EMAIL` VARCHAR(32)  UNIQUE COMMENT "邮箱",
	`STATUS` INT NOT NULL COMMENT "状态",
	`CREATE_TIME` DATETIME COMMENT "创建时间",
	`UPDATE_TIME` DATETIME COMMENT "更新时间",
	`DELETE_TIME` DATETIME COMMENT "删除时间",
	PRIMARY KEY(`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `sys_role`(
	`ID` VARCHAR(32) COMMENT "ID",
	`MENU_IDS` VARCHAR(32) COMMENT "菜单ID",
	`CODE` VARCHAR(32) UNIQUE COMMENT "编号",
	`NAME` VARCHAR(32) UNIQUE COMMENT "名称",
	`STATUS` INT NOT NULL COMMENT "状态",
	`CREATE_TIME` DATETIME COMMENT "创建时间",
	`UPDATE_TIME` DATETIME COMMENT "更新时间",
	`DELETE_TIME` DATETIME COMMENT "删除时间",
	PRIMARY KEY(`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `sys_menu`(
	`ID` VARCHAR(32) COMMENT "ID",
	`PARENT_ID` VARCHAR(32) COMMENT "父节点ID",
	`CODE` VARCHAR(32) UNIQUE COMMENT "编号",
	`NAME` VARCHAR(32) UNIQUE COMMENT "名称",
	`URL` VARCHAR(128) COMMENT "页面URL",
	`SORT` INT COMMENT "排序",
	`STATUS` INT NOT NULL COMMENT "状态",
	`CREATE_TIME` DATETIME COMMENT "创建时间",
	`UPDATE_TIME` DATETIME COMMENT "更新时间",
	`DELETE_TIME` DATETIME COMMENT "删除时间",
	PRIMARY KEY(`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;